### PR TITLE
Fix Satisfier Display

### LINKED ISSUE #56: Select menues are reset after textbox entry is used to update data
There needs to be some code put in around line 30 in classloader.js to check if a class is selected for a satisfied requirement. Possible use local storage data to determine this instead of ui.

### PR DESCRIPTION
**Pull request by jkingsman**
Closes #56. If this isn't reviewed by tomorrow morning I'll and merge so things aren't broken for demo.

### CODE REVIEW

File: js/helpers.js [hunk 1]
```diff
@@ -186,6 +186,7 @@ function restoreStatus() {
         }
 
         $('#' + className + 'dropdown').val(classData.date);
+        $('#' + className + 'satisfaction').val(classData.satisfaction);
```
Comment (jkingsman) [inline js/helpers.js:189]: We weren't populating the refreshed/restored page with the satisfier; as soon as a UI change was written, it would overwrite what was in storage. When we restore it the UI, that problem doesn't happen since later saves/restores are using good data.

File: js/helpers.js [hunk 2]
```diff
@@ -41,7 +41,7 @@ function drawCalendar() {
     $.each(reqs, function(reqName, classData) {
         // set which class satisfied it
         var classSatisfier = '';
-        if (classData.satisfaction != 'notselected') {
+        if ($('#' + reqName + 'satisfaction')[0].length > 2 && classData.satisfaction !== 'notselected') {
```
Comment (jkingsman) [inline js/helpers.js:44]: Logic I thought we already implemented but maybe it got refactored away -- don't display the satisfier if it's a 1:1 class (satisfier dropdown length < 3 -- the default select and the one class).

**Comment by RyanLoringCooper** [comment]
Works great. Merge when you're ready.
